use_frameworks!

def my_pods
  pod 'RxSwift', '~> 3.4'
  pod 'SwiftyJSON'
  pod 'Gifu'
end

target 'iGif' do
  my_pods
end

target 'iGifTests' do
  my_pods
  pod 'Nimble'
  pod 'RxNimble'
  pod 'RxBlocking'
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
